# Generated by Django 5.1.4 on 2024-12-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msr_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_model',
            name='project_description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project_model',
            name='project_name',
            field=models.CharField(max_length=20),
        ),
    ]
